spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pokerjava3
    username: postgres
    password: toor
    hikari:
      minimumIdle: 10
      maximumPoolSize: 100
      idleTimeout: 10000
      connectionTimeout: 3000000
      leakDetectionThreshold: 15000000
    
  profiles:
    active: dev
  servlet:
    multipart:
     maxFileSize: 300MB  
     maxRequestSize: 300MB
# JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:  
        jdbc.lob.non_contextual_creation: true
   
   
security:
 jwt:
  token:
   secret-key: secret-key
   expire-length: 99999999
